// 페이지 넘나들때 리랜더링 안하고 싶으면 Layout.tsx
// 페이지 넘나들때 리랜더링(새로 마운트) 되게 하고싶으면 Template.tsx
// Template: 예를들어 페이지 넘나들며 기록을 해야할 때 (GA 등)
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AfterLoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* AfterLoginLayout */}
      {children}
    </div>
  );
}
